### ISSUE TITLE
No longer works with latest Home Assistant (0.88)

### ISSUE THREAD

**Issue by danieljmiles** [custom-components/media_player.braviatv_psk#2]
With the latest home assistant, the component is no longer loaded with error as follows:

>2019-02-21 20:34:41 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.media_player.braviatv_psk. Make sure all dependencies are installed 
Traceback (most recent call last): 
File "/usr/local/lib/python3.6/dist-packages/homeassistant/loader.py", line 147, in _load_file module = importlib.import_module(path) 
File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) 
File "<frozen importlib._bootstrap>", line 994, in _gcd_import 
File "<frozen importlib._bootstrap>", line 971, in _find_and_load 
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked 
File "<frozen importlib._bootstrap_external>", line 678, in exec_module 
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
File "/home/<user>/.homeassistant/custom_components/media_player/braviatv_psk.py", line 12, in <module> from homeassistant.components.media_player import ( ImportError: cannot import name 'SUPPORT_TURN_ON' 2019-02-21 20:34:41 
ERROR (MainThread) [homeassistant.loader] Unable to find platform braviatv_psk

**Comment by Joeboyc2** [comment]
Unfortunately I get the same issue :-(

**Comment by gerard33** [comment]
I have it fixed on my dev system. Indeed some changes in 0.88 which means the component needs to be updated.
Will release a new version this evening.

**Comment by Joeboyc2** [comment]
Great stuff, thank you for the quick work on the is @gerard33

**Comment by glassbase** [comment]
To anyone reading this and wants to fix it for 0.88 before @gerard33 gets it updated...

Change:
```
from homeassistant.components.media_player import (
    SUPPORT_NEXT_TRACK, SUPPORT_PAUSE, SUPPORT_PREVIOUS_TRACK, SUPPORT_TURN_ON,
    SUPPORT_TURN_OFF, SUPPORT_VOLUME_MUTE, SUPPORT_VOLUME_STEP, SUPPORT_PLAY,
    SUPPORT_PLAY_MEDIA, SUPPORT_VOLUME_SET, SUPPORT_SELECT_SOURCE,
    MediaPlayerDevice, PLATFORM_SCHEMA, MEDIA_TYPE_TVSHOW, SUPPORT_STOP)
from homeassistant.const import (
    CONF_HOST, CONF_NAME, CONF_MAC, STATE_OFF, STATE_ON)
import homeassistant.helpers.config_validation as cv
```
to
```
from homeassistant.components.media_player import (
    MediaPlayerDevice, PLATFORM_SCHEMA)
from homeassistant.components.media_player.const import (
    SUPPORT_NEXT_TRACK, SUPPORT_PAUSE, SUPPORT_PREVIOUS_TRACK, SUPPORT_TURN_ON,
    SUPPORT_TURN_OFF, SUPPORT_VOLUME_MUTE, SUPPORT_VOLUME_STEP, SUPPORT_PLAY,
    SUPPORT_PLAY_MEDIA, SUPPORT_VOLUME_SET, SUPPORT_SELECT_SOURCE,
    MEDIA_TYPE_TVSHOW, SUPPORT_STOP)
from homeassistant.const import (
    CONF_HOST, CONF_NAME, CONF_MAC, STATE_OFF, STATE_ON)
import homeassistant.helpers.config_validation as cv
```

(not necessary yet, but HA warns you to change the file structure) 
Move the file from `media_player/braviatv_psk.py` to `braviatv_psk/media_player.py`

**Comment by gerard33** [comment]
Allright, updated the version. Should also be backwards compatible for those who update and are still on HA <= 0.87.

Can you please try and confirm if it works?

**Comment by danieljmiles** [comment]
Confirmed working perfectly - thanks a lot mate, really appreciate your work.

**Comment by SergiStef** [comment]
Thanks for the quick update Gerard!
